[package]
name = "my_threads"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_threads"
path = "threads.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version="0.16.0", features = ["extension-module"] }
