[package]
name = "my_threads"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_threads"
path = "src/other/rust/threads.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.15.1", features = ["extension-module"] }
